name: epg

services:
  epg:
    image: localhost/epg:latest
    container_name: epg

    ports:
      - "5000:3000"          # keep if you still want host access; safe to remove if internal-only

    volumes:
      - /PlexStorage/epg/public:/epg/public:rw,Z
      - /PlexStorage/epg/channels.xml:/epg/channels.xml:rw,Z

    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Australia/Melbourne
      CRON_SCHEDULE: "0 0 * * *"
      MAX_CONNECTIONS: "1"
      GZIP: "true"
      DAYS: "14"
      TIMEOUT: "1000"
      DELAY: "100"
      RUN_AT_STARTUP: "true"

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/"]
      interval: 30s
      timeout: 3s
      retries: 3

    restart: unless-stopped
    networks:
      - shared

networks:
  shared:
    external: true

